#!/usr/bin/env bash
#
# changelog_index.sh - render the series index of doc/changelog/CHANGELOG.md
# from the series files themselves.
#
# Usage:
#   changelog_index.sh [changelog-dir]            # print the block
#   changelog_index.sh --write [changelog-dir]    # rewrite it in place
#
# WHY IT IS GENERATED. The changelog is one file per 0.Y series behind an
# index, and an index is a roster: a list of the files that exist, which
# nothing checks unless something can re-derive it. A hand-written one goes
# stale on the first series nobody remembers to add, and the stale form is
# invisible -- a missing row reads exactly like a series that does not
# exist. So the block between the two markers is DERIVED from the series
# files, this script is what derives it, and
# script/test/drivers/changelog_layout.sh re-derives it in the lint phase
# and fails on any difference. Same generator/checker split as
# script/test/sync-doc-counts.sh and the doc-counts drift gate.
#
# WHAT A ROW CARRIES, and why that and not a table of contents. The reader
# this file is for is a downstream maintainer mid-upgrade asking "what
# changed between my version and the target, and what will break me". So
# each row is the series, its file, the dates it spans, how many versions it
# holds -- and, indented under it, the BREAKING entries. Those one-liners
# are the part an upgrader actually needs; without them an index is a list
# of filenames and the reader has to open all of them anyway.
#
# The one-liners are QUOTED, never summarised: an entry's own lead bullet,
# collapsed and stripped of its bold markers, truncated at a fixed width. A
# generator that wrote its own prose about a released entry would be
# inventing history, and there would be nothing to check it against.
#
# An entry counts as BREAKING when it sits under a `### BREAKING...` heading
# or its lead bullet names BREAKING. Both spellings are in the record: the
# roster heading is new, and the older sections marked it inline
# (`(**BREAKING**: ...)`, `### Changed (BREAKING)`), so reading only the
# heading would silently drop most of the history this index exists to
# surface.
#
# Sourceable: strict mode lives in main(), not at file scope.

_CHANGELOG_INDEX_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" \
  &> /dev/null && pwd)"
readonly _CHANGELOG_INDEX_DIR

# The markers delimiting the generated block inside CHANGELOG.md. HTML
# comments so they do not render, and a stated generator so the next person
# to edit the block by hand is told where the text comes from.
readonly _CHANGELOG_INDEX_BEGIN='<!-- changelog-index: begin -- generated by script/release/changelog_index.sh; refresh with: just release changelog-index -->'
readonly _CHANGELOG_INDEX_END='<!-- changelog-index: end -->'

# How much of a BREAKING entry's lead bullet the index quotes. Long enough
# to carry the claim, short enough that a row stays one line in a terminal.
readonly _CHANGELOG_INDEX_QUOTE=96

err() { printf '[changelog-index] %s\n' "$*" >&2; }

# _ci_collapse <line> -- the line with whitespace runs collapsed to single
# spaces and both ends trimmed. The index quotes what an entry says, not how
# it happened to be wrapped.
_ci_collapse() {
  local _out
  _out="$(printf '%s' "$*" | LC_ALL=C tr -s '[:space:]' ' ')"
  _out="${_out# }"
  _out="${_out% }"
  printf '%s' "${_out}"
}

# _ci_quote <entry-line>... -- the one-liner the index prints for a BREAKING
# entry: the lines joined, the bullet marker dropped, bold markers stripped,
# collapsed, and truncated on a word boundary.
_ci_quote() {
  local _text
  _text="$(_ci_collapse "$*")"
  _text="${_text#- }"
  _text="${_text//\*\*/}"
  if (( ${#_text} > _CHANGELOG_INDEX_QUOTE )); then
    _text="${_text:0:_CHANGELOG_INDEX_QUOTE}"
    _text="${_text% *}..."
  fi
  printf '%s' "${_text}"
}

# _ci_sort_series -- series names on stdin, newest first.
_ci_sort_series() { sort -t. -k1.2,1nr -k2,2nr; }

# _ci_render <dir> -- the whole block, markers included, on stdout.
_ci_render() {
  local _dir="${1}" _file _series
  printf '%s\n' "${_CHANGELOG_INDEX_BEGIN}"
  printf '\n'
  while IFS= read -r _series; do
    _file="${_dir}/${_series}.md"
    [[ -f "${_file}" ]] || continue
    _ci_series_block "${_series}" "${_file}"
  done < <(_ci_series_names "${_dir}" | _ci_sort_series)
  printf '\n'
  printf '%s\n' "${_CHANGELOG_INDEX_END}"
}

# _ci_series_block <series> <file> -- one series' row and its BREAKING
# one-liners.
#
# The quote is taken over the whole ENTRY -- the lead bullet plus its
# continuation lines -- and not over the lead LINE. Quoting the line ends
# the sentence wherever the author's wrapping happened to fall, which reads
# as a claim that stops mid-thought rather than as a quote that was
# shortened; over the entry, a truncation is a truncation and says so.
_ci_series_block() {
  local _series="${1}" _file="${2}"
  local -a _lines=() _dates=() _quotes=() _entry=()
  local _i _j _versions=0 _unreleased=0 _heading='' _fence='' _date _breaking
  mapfile -t _lines < "${_file}"

  for (( _i = 0; _i < ${#_lines[@]}; _i++ )); do
    # A fenced block is structurally inert here as it is in the lint: a
    # `## [` inside a ```markdown example is an example of a heading, and
    # counting it would inflate a series' version count with nothing in the
    # rendered index to show where the number came from.
    if [[ "${_lines[_i]}" =~ ^[[:space:]]*(\`\`\`+|~~~+) ]]; then
      if [[ -z "${_fence}" ]]; then
        _fence="${BASH_REMATCH[1]:0:1}"
      elif [[ "${BASH_REMATCH[1]:0:1}" == "${_fence}" ]]; then
        _fence=''
      fi
      continue
    fi
    [[ -n "${_fence}" ]] && continue
    case "${_lines[_i]}" in
      '## [Unreleased]'*)
        _unreleased=1
        _heading=''
        continue
        ;;
      '## ['*)
        _versions=$(( _versions + 1 ))
        _heading=''
        _date="${_lines[_i]#*] - }"
        [[ "${_date}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2} ]] \
          && _dates+=("${BASH_REMATCH[0]}")
        continue
        ;;
      '### '*)
        _heading="${_lines[_i]#\#\#\# }"
        continue
        ;;
      '- '*) ;;
      *) continue ;;
    esac

    _entry=("${_lines[_i]}")
    for (( _j = _i + 1; _j < ${#_lines[@]}; _j++ )); do
      [[ -z "${_lines[_j]// }" ]] && break
      [[ "${_lines[_j]}" == '#'* ]] && break
      [[ "${_lines[_j]}" == '- '* ]] && break
      _entry+=("${_lines[_j]}")
    done

    _breaking=0
    [[ "${_heading}" == BREAKING* ]] && _breaking=1
    [[ "${_heading}" == *'(BREAKING)'* ]] && _breaking=1
    [[ "${_lines[_i]}" == *BREAKING* ]] && _breaking=1
    [[ "${_breaking}" -eq 1 ]] && _quotes+=("$(_ci_quote "${_entry[@]}")")
  done

  _ci_row "${_series}" "${_versions}" "${_unreleased}" "${_dates[@]}"
  local _quote
  for _quote in "${_quotes[@]}"; do
    printf '  - %s\n' "${_quote}"
  done
}

# _ci_series_names <dir> -- the basename of every series file, one per line.
_ci_series_names() {
  local _file _name
  for _file in "${1}"/v*.md; do
    [[ -f "${_file}" ]] || continue
    _name="$(basename "${_file}" .md)"
    [[ "${_name}" =~ ^v[0-9]+\.[0-9]+$ ]] || continue
    printf '%s\n' "${_name}"
  done
}

# _ci_row <series> <version-count> <has-unreleased> <date>... -- the
# series' own line.
#
# "in progress" MEANS "carries [Unreleased]", in both directions, and the
# index's own prose is why: it tells a writer that the next entry goes into
# "the row below marked *in progress*", so the marker is a navigation
# instruction and nothing else may render it. The layout lint guarantees
# exactly one series file carries the heading, so exactly one row says it.
#
# It used to be derived from the version count instead, which agreed with
# the live series only by coincidence -- a series with a released version of
# its own said "(plus [Unreleased])" and left the words the prose names on
# no row at all, while a stub cut and not yet written into claimed them. A
# marker that names the wrong row is worse than an absent one: the reader
# does what it says.
_ci_row() {
  local _series="${1}" _versions="${2}" _unreleased="${3}"
  shift 3
  # 'undated' is the span of a released section whose heading carries no
  # ISO date for the caller to collect. That fallback used to be
  # 'in progress' too, which handed the live-series marker to a row on the
  # strength of a missing date.
  local _span='undated' _noun='versions' _live=''
  [[ "${_versions}" -eq 1 ]] && _noun='version'
  [[ "${_unreleased}" -eq 1 ]] && _live=', in progress'
  if [[ "${_versions}" -eq 0 ]]; then
    # No date to borrow: a series with nothing released has no span. The
    # live one says so; the other says it is empty rather than silently
    # rendering the same words the live one does.
    _span='no versions yet'
    [[ "${_unreleased}" -eq 1 ]] && _span='in progress'
    printf -- '- **[%s](%s.md)** -- %s\n' "${_series}" "${_series}" "${_span}"
    return 0
  fi
  if [[ "$#" -gt 0 ]]; then
    # Min and max in-shell, not `| sort | head -n1`: a reader that stops
    # reading strands the writer with SIGPIPE, and under pipefail that 141
    # becomes the pipeline's status. ISO-8601 dates compare correctly as
    # strings, so there is nothing sort was doing that `<` does not.
    local _oldest="${1}" _newest="${1}" _d
    for _d in "$@"; do
      [[ "${_d}" < "${_oldest}" ]] && _oldest="${_d}"
      [[ "${_d}" > "${_newest}" ]] && _newest="${_d}"
    done
    if [[ "${_oldest}" == "${_newest}" ]]; then
      _span="${_newest}"
    else
      _span="${_oldest} .. ${_newest}"
    fi
  fi
  printf -- '- **[%s](%s.md)** -- %s, %d %s%s\n' \
    "${_series}" "${_series}" "${_span}" "${_versions}" "${_noun}" "${_live}"
}

# _ci_write <dir> -- replace the block inside <dir>/CHANGELOG.md. The
# markers are matched with awk's index(), not a sed address: they carry
# backticks, slashes and brackets, and a regex-escaped address for them is a
# second place the marker text has to be got exactly right.
#
# The three strings reach awk through the ENVIRONMENT, not through `-v`.
# awk expands backslash escape sequences in a -v assignment, so a BREAKING
# lead bullet quoting a `\n` -- and this repo's entries do quote `\n`, `\r`
# and `\t` when the change is about one -- would be written back with a real
# newline in it. The layout lint would then refuse the file, and
# `just release changelog-index`, the fix that lint's own message names,
# would reproduce the same corruption on every run. ENVIRON values are
# taken literally.
_ci_write() {
  local _dir="${1}" _index="${1}/CHANGELOG.md" _tmp _rendered
  if [[ ! -f "${_index}" ]]; then
    err "REFUSING: no index at ${_index}."
    return 1
  fi
  if ! grep -qF -- "${_CHANGELOG_INDEX_BEGIN}" "${_index}" \
    || ! grep -qF -- "${_CHANGELOG_INDEX_END}" "${_index}"; then
    err "REFUSING: ${_index} carries no changelog-index markers to replace."
    return 1
  fi
  _rendered="$(_ci_render "${_dir}")"
  _tmp="$(mktemp)"
  _CI_BEGIN="${_CHANGELOG_INDEX_BEGIN}" \
  _CI_END="${_CHANGELOG_INDEX_END}" \
  _CI_BLOCK="${_rendered}" \
  awk '
    BEGIN {
      begin = ENVIRON["_CI_BEGIN"]
      end   = ENVIRON["_CI_END"]
      block = ENVIRON["_CI_BLOCK"]
    }
    $0 == begin { print block; skip = 1; next }
    $0 == end   { skip = 0; next }
    !skip
  ' "${_index}" > "${_tmp}"
  # mktemp creates 0600. Without this the documented refresh leaves the
  # changelog owner-only-readable in the working tree, on a bit git does
  # not track -- so nothing downstream reports it and the next reader has
  # no way to tell what changed the mode.
  chmod --reference="${_index}" "${_tmp}" 2> /dev/null || true
  mv -- "${_tmp}" "${_index}"
  printf 'changelog index: refreshed %s\n' "${_index}"
}

main() {
  # Strict mode here, not at file scope: the file is sourceable and a
  # sourced file that turns nounset on leaves it on in its caller.
  set -euo pipefail

  local _write=0
  if [[ "${1:-}" == '--write' ]]; then
    _write=1
    shift
  fi
  local _dir="${1:-${_CHANGELOG_INDEX_DIR}/../../doc/changelog}"
  if [[ ! -d "${_dir}" ]]; then
    err "REFUSING: no changelog directory at ${_dir}."
    return 1
  fi
  if [[ -z "$(_ci_series_names "${_dir}")" ]]; then
    err "REFUSING: no vX.Y.md series file under ${_dir}." \
        "An index derived from nothing would render as an empty block and" \
        "read as a changelog with no history."
    return 1
  fi

  if [[ "${_write}" -eq 1 ]]; then
    _ci_write "${_dir}"
  else
    _ci_render "${_dir}"
  fi
}

if [[ "${BASH_SOURCE[0]:-}" == "${0:-}" ]]; then
  main "$@"
fi
