#!/usr/bin/env bash
#
# release_notes.sh - assemble the curated release notes for one tag, and
# REFUSE when what it assembled is not release notes.
#
# Usage:
#   release_notes.sh <tag> [changelog-dir]
#
#   <tag>            v0.42.0 / v0.42.0-rc4, with or without the leading `v`
#   changelog-dir    default: <repo>/doc/changelog
#
# Writes the body to stdout. Exit 0 = assembled; 1 = refused, with the
# reason on stderr.
#
# WHY IT EXISTS. The release job in .github/workflows/self-test.yaml used to
# inline this:
#
#   awk -v ver="$VERSION" '/^## \[/ { if (found) exit; ... } found' \
#     doc/changelog/CHANGELOG.md > /tmp/release-notes.md
#
# and then handed the file to softprops/action-gh-release. Nothing looked at
# the result. An awk that matches nothing exits 0 and writes an EMPTY file,
# and the action accepts an empty body_path without complaint, so a doc-only
# PR that renamed or reformatted one `## [vX.Y.Z]` heading would ship a
# release whose entire body was GitHub's autogenerated PR-title list --
# green CI, no warning, and the curated notes silently absent. This script
# is that extraction with the assertions the pipeline never had, in a file a
# spec can drive.
#
# WHY THE UNION. This project cuts RCs and promotes one unchanged, and the
# convention was to leave the entries under the RC headings that introduced
# them and give the final section a paragraph pointing at them. Measured on
# the real v0.42.0 release page: 26,690 characters, of which the human-
# written part was five lines saying the entries are somewhere else. RC
# structure is an internal artifact -- a reader of `v0.42.0` has no interest
# in which RC introduced what -- so a final release's notes are the union of
# its own section and every `-rcN` section under it, merged category by
# category so each category is one list.
#
# That merge is a few lines only because the category set is locked
# (script/release/changelog_categories.sh). Categories are emitted in roster
# order, and a historical heading outside the roster is emitted after them
# in first-seen order rather than dropped -- released text is a record, and
# the roster governs what is written from now on, not what shipped.
#
# THE POINTER PARAGRAPH. Prose sitting under the version heading before the
# first `### ` is a lead paragraph. The leading section's is kept; an RC's
# is not, because an RC's lead says which candidate this is and a reader of
# the final tag is not being told that. The one exception, in both
# directions, is a lead that CARRIES AN ENTRY: a `- ` bullet under no
# heading is an entry that happens to sit above the first one, not prose,
# and it is kept along with the sentence that introduces it.
#
# That exception is the difference between a pointer paragraph and a
# promoted release that wrote its entries where it stood. The rule used to
# be "the section has no `### ` of its own, so its whole body is a pointer",
# which is the v0.42.0 shape -- five lines saying the entries are elsewhere.
# It is not the v0.29.0 shape, whose pointer prose ends in three bullets
# naming the downstream propagation queued for that release: the rule read
# the section for headings and never the lead for content, and dropped all
# three. Measured across the real tree it dropped entries from five of the
# tags it was run on.
#
# WHAT IT REFUSES. A body over GitHub's 125,000-character release-body cap
# (the union of v0.42's four RCs is 326,638, so this is not hypothetical --
# handing it over would be a 422 at tag push, after every gate has passed);
# no section for the tag; a tag whose section appears in
# more than one file (the split's own failure mode -- a section copied
# rather than moved leaves two answers to "what shipped", and picking either
# silently is how the wrong one reaches a release page); an assembled
# body carrying no entry bullet at all (the v0.42.0 shape with no RCs to
# union in -- a refusal rather than a short body because a release page with
# no notes is exactly what this script exists to stop shipping); and an
# assembled body carrying FEWER entry bullets than the sections it was
# merged from.
#
# That last one is a postcondition, not a shape check, and it is here
# because the mechanism it guards has already failed once. `grep -q '^- '`
# over the whole body passes as long as one bulleted category survived, so
# an entry the merge could not file was indistinguishable from a release
# with a single category -- and the release job publishes this body ALONE
# (`generate_release_notes: false`), so a dropped entry has no second
# source. Counting the entries in and out costs one pass and turns the next
# shape this file was not written for into a refusal at tag push rather
# than a release page nobody knows is short.
#
# Fenced code blocks are structurally inert, as in the changelog lint: the
# file documents its own format in ```markdown examples, so a `## [` inside
# a fence is an example of a heading and must not end a section.

# Where this script lives, so the default changelog directory resolves
# without a caller having to know the layout.
_RELEASE_NOTES_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" \
  &> /dev/null && pwd)"
readonly _RELEASE_NOTES_DIR

# GitHub's cap on a release body. A body over it is rejected by the API
# with a 422, so the choice is to find that out here or at tag push after
# every gate has passed.
readonly _RELEASE_NOTES_MAX=125000

err() { printf '[release-notes] %s\n' "$*" >&2; }

# Per-tag index of the changelog tree, filled by _index_sections:
# tag -> file, and the 0-based half-open body range within that file.
declare -A _RN_FILE=()
declare -A _RN_START=()
declare -A _RN_END=()

# The delimiter character of the fence _is_fence_delimiter last matched.
_RN_FENCE_CHAR=''

# _is_fence_delimiter <line> -- does the line open or close a fenced code
# block? Sets _RN_FENCE_CHAR to the delimiter's character when it does.
_is_fence_delimiter() {
  local _trimmed="${1#"${1%%[![:space:]]*}"}"
  if [[ "${_trimmed}" =~ ^(\`\`\`+|~~~+) ]]; then
    _RN_FENCE_CHAR="${BASH_REMATCH[1]:0:1}"
    return 0
  fi
  return 1
}

# _ends_section <line> -- does the line end the body of a version section?
# A level-2 heading starts the next one; a link definition at column 0 is
# the compare-link block at the foot of a series file, which is reference
# data and not part of anyone's notes.
_ends_section() {
  [[ "${1}" == '## '* ]] && return 0
  [[ "${1}" =~ ^\[[^]]+\]:[[:space:]] ]] && return 0
  return 1
}

# _index_sections <dir> -- index every `## [<tag>]` section under <dir>/*.md.
# A tag found twice is fatal: two answers to "what shipped in this tag" is
# not a thing to resolve by preferring one file.
_index_sections() {
  local _dir="${1}" _file _tag _open='' _fence=''
  local -a _lines=()
  local _i
  for _file in "${_dir}"/*.md; do
    [[ -f "${_file}" ]] || continue
    mapfile -t _lines < "${_file}"
    _open=''
    _fence=''
    for (( _i = 0; _i < ${#_lines[@]}; _i++ )); do
      if _is_fence_delimiter "${_lines[_i]}"; then
        if [[ -z "${_fence}" ]]; then
          _fence="${_RN_FENCE_CHAR}"
        elif [[ "${_RN_FENCE_CHAR}" == "${_fence}" ]]; then
          _fence=''
        fi
        continue
      fi
      [[ -n "${_fence}" ]] && continue
      _ends_section "${_lines[_i]}" || continue
      if [[ -n "${_open}" ]]; then
        _RN_END["${_open}"]="${_i}"
        _open=''
      fi
      [[ "${_lines[_i]}" =~ ^##\ \[([^]]+)\] ]] || continue
      _tag="${BASH_REMATCH[1]}"
      if [[ -n "${_RN_FILE["${_tag}"]:-}" ]]; then
        err "REFUSING: '${_tag}' has a section in both" \
            "${_RN_FILE["${_tag}"]} and ${_file}. A section copied rather" \
            "than moved leaves two answers to what shipped in that tag."
        return 1
      fi
      _RN_FILE["${_tag}"]="${_file}"
      _RN_START["${_tag}"]=$(( _i + 1 ))
      _RN_END["${_tag}"]="${#_lines[@]}"
      _open="${_tag}"
    done
  done
  return 0
}

# _section_body <tag> -- the section's body lines on stdout.
_section_body() {
  local _tag="${1}" _i
  local -a _lines=()
  mapfile -t _lines < "${_RN_FILE["${_tag}"]}"
  for (( _i = _RN_START["${_tag}"]; _i < _RN_END["${_tag}"]; _i++ )); do
    printf '%s\n' "${_lines[_i]}"
  done
}

# _rc_tags <final-tag> -- the tag's release candidates, oldest first. A
# release candidate of `vX.Y.Z` is `vX.Y.Z-rcN`; the numeric sort is what
# keeps rc10 after rc9 rather than after rc1.
_rc_tags() {
  local _final="${1}" _tag
  for _tag in "${!_RN_FILE[@]}"; do
    [[ "${_tag}" =~ ^"${_final}"-rc([0-9]+)$ ]] || continue
    printf '%s %s\n' "${BASH_REMATCH[1]}" "${_tag}"
  done | sort -n | cut -d' ' -f2
}

# _trim_blank_edges -- drop leading AND trailing blank lines from stdin.
# The lead paragraph needs both ends: a `## [tag]` heading is always
# followed by a blank line, so the first line of a lead is always blank.
_trim_blank_edges() {
  local -a _buf=()
  local _line _i _first=-1 _last=-1
  while IFS= read -r _line; do
    _buf+=("${_line}")
    if [[ -n "${_line// }" ]]; then
      [[ "${_first}" -lt 0 ]] && _first=$(( ${#_buf[@]} - 1 ))
      _last=$(( ${#_buf[@]} - 1 ))
    fi
  done
  if [[ "${_first}" -ge 0 ]]; then
    for (( _i = _first; _i <= _last; _i++ )); do
      printf '%s\n' "${_buf[_i]}"
    done
  fi
}

# _trim_trailing_blanks -- drop trailing blank lines from stdin.
_trim_trailing_blanks() {
  local -a _buf=()
  local _line _i _last=-1
  while IFS= read -r _line; do
    _buf+=("${_line}")
    [[ -n "${_line// }" ]] && _last=$(( ${#_buf[@]} - 1 ))
  done
  for (( _i = 0; _i <= _last; _i++ )); do
    printf '%s\n' "${_buf[_i]}"
  done
}

# _assemble <tag>... -- merge the given sections, first tag leading, into
# one lead paragraph plus one list per category, on stdout.
_assemble() {
  local -a _tags=("$@")
  local -A _bucket=()
  local -a _order=()
  local -a _lead=() _leads=()
  local _tag _line _current='' _own_headings=0 _first=1 _key _fence=''
  local _lead_entries=0 _lead_text=''
  local -a _body=()

  for _tag in "${_tags[@]}"; do
    mapfile -t _body < <(_section_body "${_tag}")
    _current=''
    _fence=''
    _lead=()
    _lead_entries=0
    _own_headings=0
    for _line in "${_body[@]}"; do
      if _is_fence_delimiter "${_line}"; then
        if [[ -z "${_fence}" ]]; then
          _fence="${_RN_FENCE_CHAR}"
        elif [[ "${_RN_FENCE_CHAR}" == "${_fence}" ]]; then
          _fence=''
        fi
      fi
      if [[ -z "${_fence}" ]] && [[ "${_line}" == '### '* ]]; then
        _current="${_line#\#\#\# }"
        _current="${_current%"${_current##*[![:space:]]}"}"
        if [[ -z "${_bucket["${_current}"]+set}" ]]; then
          _bucket["${_current}"]=''
          _order+=("${_current}")
        fi
        _own_headings=$(( _own_headings + 1 ))
        continue
      fi
      if [[ -z "${_current}" ]]; then
        _lead+=("${_line}")
        if [[ -z "${_fence}" && "${_line}" == '- '* ]]; then
          _lead_entries=$(( _lead_entries + 1 ))
        fi
        continue
      fi
      _bucket["${_current}"]+="${_line}"$'\n'
    done

    # Keep this section's lead when it carries an entry -- a `- ` bullet
    # under no heading is an entry that sits above the first one, and the
    # sentence introducing it is what says what the list is. Otherwise keep
    # only the LEADING section's, and only when that section wrote entries
    # of its own: a prose-only lead from a section with no `### ` is the
    # promoted-release pointer at the RCs whose union replaces it, and an
    # RC's own lead names the candidate, which the final tag's reader is
    # not being told.
    #
    # The guard is on the TEXT, not on the line count. A `## [tag]` heading
    # is always followed by a blank line, so _lead is never an empty array
    # -- only ever an array of blanks -- and a count-based guard therefore
    # fires for every release that wrote no lead at all, emitting a blank
    # line ahead of the first `### `. Every assembled body opened with one.
    _lead_text=''
    if [[ "${#_lead[@]}" -gt 0 ]] \
      && { [[ "${_lead_entries}" -gt 0 ]] \
        || [[ "${_first}" -eq 1 && "${_own_headings}" -gt 0 ]]; }; then
      _lead_text="$(printf '%s\n' "${_lead[@]}" | _trim_blank_edges)"
    fi
    [[ -n "${_lead_text}" ]] && _leads+=("${_lead_text}")
    _first=0
  done

  local _i
  for (( _i = 0; _i < ${#_leads[@]}; _i++ )); do
    printf '%s\n' "${_leads[_i]}"
    printf '\n'
  done

  # Roster order first, then whatever history left behind, in first-seen
  # order. A shipped heading outside the roster is a record, not a defect.
  local -a _emitted=()
  for _key in "${CHANGELOG_CATEGORIES[@]}"; do
    [[ -n "${_bucket["${_key}"]+set}" ]] || continue
    _emit_category "${_key}" "${_bucket["${_key}"]}"
    _emitted+=("${_key}")
  done
  for _key in "${_order[@]}"; do
    _in_list "${_key}" "${_emitted[@]}" && continue
    _emit_category "${_key}" "${_bucket["${_key}"]}"
    _emitted+=("${_key}")
  done
}

# _in_list <needle> <haystack>... -- is the needle in the list?
_in_list() {
  local _needle="${1}" _item
  shift
  for _item in "$@"; do
    [[ "${_item}" == "${_needle}" ]] && return 0
  done
  return 1
}

# _count_entries -- how many entry bullets stdin carries, outside fenced
# blocks. A `- ` at column 0 is the unit the changelog is written in and the
# unit the entry lint measures; a continuation line and a nested bullet are
# indented and belong to the entry above them.
_count_entries() {
  local _line _fence='' _n=0
  while IFS= read -r _line; do
    if _is_fence_delimiter "${_line}"; then
      if [[ -z "${_fence}" ]]; then
        _fence="${_RN_FENCE_CHAR}"
      elif [[ "${_RN_FENCE_CHAR}" == "${_fence}" ]]; then
        _fence=''
      fi
      continue
    fi
    [[ -n "${_fence}" ]] && continue
    [[ "${_line}" == '- '* ]] && _n=$(( _n + 1 ))
  done
  printf '%s' "${_n}"
}

# _emit_category <name> <body> -- one heading and its merged list.
_emit_category() {
  printf '### %s\n' "${1}"
  printf '%s' "${2}" | _trim_trailing_blanks
  printf '\n'
}

main() {
  # Strict mode is set HERE, not at file scope: this file carries the
  # `BASH_SOURCE == $0` guard, so it is sourceable, and a sourced file that
  # turns nounset on leaves it on in its caller.
  set -euo pipefail

  local _tag="${1:-}"
  if [[ -z "${_tag}" ]]; then
    err "usage: release_notes.sh <tag> [changelog-dir]"
    return 2
  fi
  [[ "${_tag}" == v* ]] || _tag="v${_tag}"
  local _dir="${2:-${_RELEASE_NOTES_DIR}/../../doc/changelog}"
  if [[ ! -d "${_dir}" ]]; then
    err "REFUSING: no changelog directory at ${_dir}."
    return 1
  fi

  # shellcheck source=script/release/changelog_categories.sh
  source "${_RELEASE_NOTES_DIR}/changelog_categories.sh"

  _index_sections "${_dir}" || return 1
  if [[ -z "${_RN_FILE["${_tag}"]:-}" ]]; then
    err "REFUSING: no '## [${_tag}]' section under ${_dir}." \
        "The tag's notes would have been empty, and an empty body ships a" \
        "release page carrying only GitHub's autogenerated PR titles."
    return 1
  fi

  local -a _sources=("${_tag}")
  if [[ "${_tag}" != *-* ]]; then
    local _rc
    while IFS= read -r _rc; do
      [[ -n "${_rc}" ]] && _sources+=("${_rc}")
    done < <(_rc_tags "${_tag}")
  fi

  local _notes
  _notes="$(_assemble "${_sources[@]}")"
  if ! grep -q '^- ' <<< "${_notes}"; then
    err "REFUSING: the assembled notes for ${_tag} carry no entry." \
        "Sections read: ${_sources[*]}. A promoted release whose section" \
        "only points at its RCs needs those RC sections present to union."
    return 1
  fi

  # The merge is complete or the release fails here. Counted rather than
  # trusted because the last thing that went wrong in this file went wrong
  # in silence: entries the merge could not file under a category were
  # dropped, and the guard above passed on the categories that survived.
  local _source_entries=0 _emitted_entries _rc_entries
  local _source
  for _source in "${_sources[@]}"; do
    _rc_entries="$(_section_body "${_source}" | _count_entries)"
    _source_entries=$(( _source_entries + _rc_entries ))
  done
  _emitted_entries="$(_count_entries <<< "${_notes}")"
  if (( _emitted_entries < _source_entries )); then
    err "REFUSING: the assembled notes for ${_tag} carry" \
        "${_emitted_entries} of the ${_source_entries} entry bullets their" \
        "sections hold. Sections read: ${_sources[*]}. The merge files" \
        "entries under the category heading above them, so an entry it" \
        "could not place is an entry nobody is told is missing -- and the" \
        "release job publishes this body alone" \
        "(generate_release_notes: false), so there is no second source for" \
        "it. Fix the assembler, not the changelog."
    return 1
  fi
  # Measured in BYTES, which is at least the character count GitHub
  # actually caps, so the refusal errs toward firing early rather than
  # toward a release that fails at the API.
  local _size
  _size="$(LC_ALL=C printf '%s' "${_notes}" | wc -c)"
  if (( _size > _RELEASE_NOTES_MAX )); then
    err "REFUSING: the assembled notes for ${_tag} are ${_size} bytes," \
        "over GitHub's ${_RELEASE_NOTES_MAX}-character release body limit." \
        "Sections read: ${_sources[*]}. action-gh-release would reject this" \
        "with a 422 at tag push, after every gate has passed. Truncating" \
        "silently is not the alternative: a release page missing entries" \
        "nobody was told were dropped is the failure this script exists to" \
        "stop. Shorten the entries -- the 700-character cap the changelog" \
        "lint applies to [Unreleased] keeps a release written under it well" \
        "clear of this."
    return 1
  fi
  printf '%s\n' "${_notes}"
}

if [[ "${BASH_SOURCE[0]:-}" == "${0:-}" ]]; then
  main "$@"
fi
