#!/usr/bin/env bats
#
# adr_doc_claims_spec.bats -- an ADR's claims about THIS repo are checked
# against this repo.
#
# An ADR is a record, and the half of it that rots is the mechanism
# description: the decision stays true while the file it names moves,
# changes trigger, or hands its work to another file. Nothing in the gate
# reads prose, so the rot is found by whoever next traces the record --
# which is the one moment the record is supposed to save them.
#
# ADR-00000027 shipped exactly that defect and it is the reason this spec
# exists. Its Context said a base tag triggers "the `release` job in
# `.github/workflows/self-test.yaml` plus `release-worker.yaml`, assembling
# the payload declared in `script/ci/release/archive.manifest`". Both halves
# were false: `release-worker.yaml` is `on: workflow_call` only, so no base
# tag reaches it (a DOWNSTREAM repo's tag calls it, through the `uses:` line
# `init.sh` writes into that repo's `main.yaml`), and the tag-triggered
# `release` job in `self-test.yaml` still assembles its archive from a
# hardcoded `cp -r` operand list -- it never reads the manifest. A reader
# tracing base's own release from the ADR landed on a manifest base does not
# use.
#
# Three rules, all DERIVED from the tree rather than restated from it, so a
# migration lifts the constraint instead of breaking the test:
#
#   R1 -- trigger. A block that makes a TRIGGER claim ("trigger", "tag
#         push") and names a workflow this repo has must not leave a
#         workflow with NO tag trigger looking tag-triggered: such a block
#         has to state the real trigger (`workflow_call`). Derived from the
#         workflow's own `on:` block.
#   R2 -- payload. A block that names an assembler or a payload manifest
#         attributes it to every workflow the same block names, so each of
#         those workflows must actually reference it. Derived by reading
#         the workflow file.
#   R3 -- quotation. A block that claims a VERBATIM quotation must name a
#         path that exists in this repo. A verbatim claim about a file the
#         gate cannot open is unfalsifiable here, and ADR-00000027 shipped
#         one over a table with a row silently dropped.
#
# The unit is a BLOCK -- a paragraph, or one top-level `- ` bullet and its
# continuations -- because that is the span a reader takes as one claim.
# Fenced code is inert: inside a fence a workflow name is an example.
#
# Measured before it was built, which is this repo's bar for a new rule.
# Run over all of doc/adr/*.md, an R1 keyed on the word "tag" flagged
# ADR-00000027's Context (true) and ADR-00000002's (false: it names both
# worker workflows while describing the `@vX.Y.Z` ref a downstream pins,
# which is not a trigger claim at all). Keyed on the claim instead --
# "trigger" / "tag push" -- the three rules flag ADR-00000027's two
# defective blocks and NOTHING else across every record. The other ADRs
# that name a workflow (00000026 build-worker.yaml, 00000017 / 00000016 /
# 00000012 self-test.yaml) make no trigger claim in the naming block; the
# four other ADRs using the word "verbatim" do not introduce a quotation
# with it, so R3 never considers them either.

setup() {
  export LOG_FORMAT=text
  load "${BATS_TEST_DIRNAME}/test_helper"

  REPO=/source
  ADR_DIR="${REPO}/doc/adr"
  SCRATCH="$(mktemp -d)"
}

teardown() {
  [[ -n "${SCRATCH:-}" ]] && rm -rf "${SCRATCH}"
}

# ── the checker ──────────────────────────────────────────────────────────────

# _adr_wf_tag_triggered <workflow-file> -- does a tag push reach it? Read
# off the workflow's own `on:` block (to the next column-0 key), never a
# list kept here: a workflow that gains or loses a tag trigger must move
# this answer by itself.
#
# No pipeline: the answer is captured and compared in-shell, so no exit
# status here depends on how two processes were scheduled -- the
# early-closing-reader class this repo has already had to fix once.
_adr_wf_tag_triggered() {
  local _on
  _on="$(awk '/^on:/ { o = 1; next } /^[^[:space:]#]/ { o = 0 } o' "${1}")"
  [[ "${_on}" == *"tags:"* ]]
}

# _adr_claims_block <file> <line-no> <repo> <text> -- apply R1/R2/R3 to one
# block. Prints one line per violation; returns non-zero if any.
_adr_claims_block() {
  local _file="${1}" _lineno="${2}" _repo="${3}" _text="${4}"
  local _v=0 _wf _tok _name _hit
  local -a _named=()

  # Which workflows the block names AND this repo actually has. A name this
  # repo does not carry (`main.yaml`, generated downstream;
  # `base-version-monitor.yaml`, generated by init.sh; `compose.yaml`) is
  # not a claim about a workflow file and is skipped rather than guessed at.
  _hit="$(grep -oE '[A-Za-z0-9_.-]+\.yaml' <<< "${_text}" || true)"
  while read -r _name; do
    [[ -n "${_name}" ]] || continue
    [[ -f "${_repo}/.github/workflows/${_name}" ]] || continue
    case " ${_named[*]-} " in
      *" ${_name} "*) continue ;;
    esac
    _named+=("${_name}")
  done <<< "${_hit}"

  # R1 -- trigger. Only blocks that make a TRIGGER claim are considered.
  # "tag" alone is far too wide: ADR-00000002 names both worker workflows
  # while describing the `@vX.Y.Z` refs a downstream pins them at, which
  # says nothing about what starts them, and the word "tag" is all over
  # that paragraph. Requiring the claim itself ("trigger", "tag push")
  # takes that block -- the one measured false positive -- back out while
  # still catching the shipped defect, whose sentence is "what the tag then
  # *triggers*".
  if grep -qiE 'trigger|tag push|push.*tags' <<< "${_text}"; then
    for _wf in ${_named[*]-}; do
      _adr_wf_tag_triggered "${_repo}/.github/workflows/${_wf}" && continue
      grep -q 'workflow_call' <<< "${_text}" && continue
      printf '%s:%d: names %s in a tag claim, but %s has no tag trigger and the block does not state its real trigger (workflow_call)\n' \
        "${_file}" "${_lineno}" "${_wf}" "${_wf}"
      _v=$(( _v + 1 ))
    done
  fi

  # R2 -- payload. Naming an assembler or a manifest beside a workflow
  # attributes one to the other; the workflow has to reference it.
  #
  # The workflow side is matched against its CODE, not its prose. A comment
  # saying a workflow does NOT use the manifest contains the manifest path,
  # and a plain grep reads that as the reference it is denying -- which is
  # exactly how self-test.yaml's "do not re-add one" note made this rule
  # certify the claim it exists to refuse. Stripping from an unquoted `#`
  # can also cut a `#` inside a quoted value; that direction is safe,
  # because it can only make the rule fire when it should not, never stay
  # silent when it should speak.
  for _tok in script/ci/release-archive.sh script/ci/release/archive.manifest; do
    grep -qF "${_tok}" <<< "${_text}" || continue
    for _wf in ${_named[*]-}; do
      sed 's/#.*//' "${_repo}/.github/workflows/${_wf}" \
        | grep -qF "${_tok}" && continue
      printf '%s:%d: attributes %s to %s, which does not reference it\n' \
        "${_file}" "${_lineno}" "${_tok}" "${_wf}"
      _v=$(( _v + 1 ))
    done
  done

  # R3 -- quotation. "verbatim" plus a block that INTRODUCES the quotation
  # (it ends on a colon) is a completeness claim; it has to be about a file
  # this gate can open.
  if grep -q 'verbatim' <<< "${_text}" && [[ "${_text}" == *: ]]; then
    local _found=0 _p
    _hit="$(grep -oE '`[^`]+`' <<< "${_text}" || true)"
    while read -r _p; do
      _p="${_p//\`/}"
      [[ -n "${_p}" ]] || continue
      [[ -e "${_repo}/${_p}" ]] && _found=1
    done <<< "${_hit}"
    if [[ "${_found}" -eq 0 ]]; then
      printf '%s:%d: claims a verbatim quotation of something outside this repo -- no gate can check it, so do not claim it\n' \
        "${_file}" "${_lineno}"
      _v=$(( _v + 1 ))
    fi
  fi

  [[ "${_v}" -eq 0 ]]
}

# _adr_claims <adr-file> [repo-root] -- split the ADR into blocks and check
# each. Prints every violation; returns non-zero if any.
_adr_claims() {
  local _file="${1}" _repo="${2:-${REPO}}"
  local -a _lines=() _block=()
  local _i _line _trim _in_fence=0 _start=0 _v=0 _boundary

  mapfile -t _lines < "${_file}"

  for (( _i = 0; _i <= ${#_lines[@]}; _i++ )); do
    _boundary=0
    if [[ "${_i}" -ge "${#_lines[@]}" ]]; then
      _boundary=1
    else
      _line="${_lines[_i]}"
      _trim="${_line#"${_line%%[![:space:]]*}"}"
      if [[ "${_trim}" == '```'* || "${_trim}" == '~~~'* ]]; then
        _in_fence=$(( 1 - _in_fence ))
        _boundary=1
      elif [[ "${_in_fence}" -eq 1 ]]; then
        # Fenced content: inert, and it cannot join the block around it.
        _boundary=1
      elif [[ -z "${_line// }" ]]; then
        _boundary=1
      elif [[ "${_line}" == '#'* ]]; then
        _boundary=1
      elif [[ "${_line}" == '- '* && "${#_block[@]}" -gt 0 ]]; then
        # A new top-level bullet ends the previous block and opens one.
        _boundary=2
      fi
    fi

    if [[ "${_boundary}" -ne 0 && "${#_block[@]}" -gt 0 ]]; then
      _adr_claims_block "${_file}" "$(( _start + 1 ))" "${_repo}" \
        "$(printf '%s\n' "${_block[@]}")" || _v=$(( _v + 1 ))
      _block=()
    fi
    [[ "${_i}" -ge "${#_lines[@]}" ]] && break
    if [[ "${_boundary}" -eq 0 || "${_boundary}" -eq 2 ]]; then
      [[ "${#_block[@]}" -eq 0 ]] && _start="${_i}"
      _block+=("${_line}")
    fi
  done

  [[ "${_v}" -eq 0 ]]
}

# _write_adr <name> <line>... -- a scratch ADR fixture.
_write_adr() {
  local _name="${1}"; shift
  printf '%s\n' "$@" > "${SCRATCH}/${_name}"
  printf '%s' "${SCRATCH}/${_name}"
}

# ════════════════════════════════════════════════════════════════════
# The real tree
# ════════════════════════════════════════════════════════════════════

@test "doc/adr: every record's workflow and quotation claims hold against the tree (#927)" {
  local _f _bad=0
  for _f in "${ADR_DIR}"/*.md; do
    if ! _adr_claims "${_f}" "${REPO}"; then
      _bad=$(( _bad + 1 ))
    fi
  done
  [ "${_bad}" -eq 0 ]
}

@test "doc/adr: the scan is not vacuous -- ADR-00000027 is read and holds blocks (#927)" {
  # A checker that silently reads nothing reports every tree clean. Pin
  # that the record this spec was written for is actually opened, and that
  # the block walk produces the blocks the rules are applied to.
  local _adr="${ADR_DIR}/00000027-release-cadence-and-fanout-trigger.md"
  [ -f "${_adr}" ]
  run grep -c 'self-test.yaml' "${_adr}"
  assert_success
  # The Context describes base's own release path, so the tag-triggered
  # workflow is named there.
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

# ════════════════════════════════════════════════════════════════════
# The facts the ADR's Context rests on
# ════════════════════════════════════════════════════════════════════

@test "release-worker.yaml is workflow_call-only, so no base tag reaches it (#927)" {
  local _wf="${REPO}/.github/workflows/release-worker.yaml"
  run grep -qE '^[[:space:]]+workflow_call:' "${_wf}"
  assert_success
  run _adr_wf_tag_triggered "${_wf}"
  assert_failure
}

@test "self-test.yaml IS tag-triggered, so it is what a base tag runs (#927)" {
  run _adr_wf_tag_triggered "${REPO}/.github/workflows/self-test.yaml"
  assert_success
}

# ════════════════════════════════════════════════════════════════════
# R1 -- trigger
# ════════════════════════════════════════════════════════════════════

@test "R1: FAILS a tag claim that names a workflow with no tag trigger (#927)" {
  # ADR-00000027's shipped Context, verbatim in shape: one paragraph, both
  # workflows, one tag claim covering them.
  local _adr
  _adr="$(_write_adr defect.md \
    '## Context' \
    '' \
    'What the tag then triggers is in this repo -- the `release` job in' \
    '`.github/workflows/self-test.yaml` plus `release-worker.yaml`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_failure
  assert_output --partial 'release-worker.yaml'
  assert_output --partial 'no tag trigger'
}

@test "R1: PASSES the same claim once the block states the real trigger (#927)" {
  local _adr
  _adr="$(_write_adr fixed.md \
    '## Context' \
    '' \
    '- `.github/workflows/release-worker.yaml` is `on: workflow_call` only,' \
    '  so no base tag reaches it; a downstream repo'"'"'s tag calls it.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R1: PASSES a tag claim about a workflow that IS tag-triggered (#927)" {
  local _adr
  _adr="$(_write_adr tagged.md \
    '## Context' \
    '' \
    'A base tag push runs the `release` job in' \
    '`.github/workflows/self-test.yaml`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R1: IGNORES a workflow named with no trigger claim in the block (#927)" {
  # The rule is about trigger claims, not about naming a file. ADR-00000026
  # names build-worker.yaml while discussing a guarded skip; that is not a
  # claim this rule may have an opinion about.
  local _adr
  _adr="$(_write_adr notrigger.md \
    '## Context' \
    '' \
    '`worker-selftest` calls `build-worker.yaml`, whose `build` job now' \
    'carries the guard.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R1: IGNORES a name this repo has no workflow for (#927)" {
  # `main.yaml` is generated into a downstream repo by init.sh; base has no
  # such workflow, so the block claims nothing about a file here -- even
  # though it IS a trigger claim and the rule therefore runs.
  local _adr
  _adr="$(_write_adr downstream.md \
    '## Context' \
    '' \
    'A downstream repo'"'"'s tag triggers it through the `uses:` line' \
    'init.sh writes into that repo'"'"'s `main.yaml`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R1: a workflow named inside a fenced example is inert (#927)" {
  local _adr
  _adr="$(_write_adr fenced.md \
    '## Context' \
    '' \
    'The trigger is spelled:' \
    '' \
    '```yaml' \
    '# release-worker.yaml, on a tag' \
    'on: { push: { tags: ["v*"] } }' \
    '```')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

# ════════════════════════════════════════════════════════════════════
# R2 -- payload
# ════════════════════════════════════════════════════════════════════

@test "R2: FAILS attributing the payload manifest to a workflow that never reads it (#927)" {
  local _adr
  _adr="$(_write_adr payload.md \
    '## Context' \
    '' \
    'The `release` job in `.github/workflows/self-test.yaml` assembles the' \
    'payload declared in `script/ci/release/archive.manifest` through' \
    '`script/ci/release-archive.sh`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_failure
  assert_output --partial 'script/ci/release/archive.manifest'
  assert_output --partial 'self-test.yaml'
}

@test "R2: a workflow that only MENTIONS the manifest in a comment does not count (#927)" {
  # The live shape this was found on: self-test.yaml carries a comment
  # explaining that it does NOT assemble the curated payload, and names the
  # manifest while saying so. Matching the file as prose reads that denial
  # as the reference it denies, so the rule passed the exact attribution it
  # exists to refuse.
  local _wf="${REPO}/.github/workflows/commented.yaml"
  cat > "${_wf}" <<'YAML'
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # The downstream archive is a different artifact (a curated payload,
      # declared in script/ci/release/archive.manifest), not this one.
      - run: echo no payload assembly here
YAML
  local _adr
  _adr="$(_write_adr commented.md \
    '## Context' \
    '' \
    'The `release` job in `.github/workflows/commented.yaml` assembles the' \
    'payload declared in `script/ci/release/archive.manifest`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_failure
  assert_output --partial 'script/ci/release/archive.manifest'
  assert_output --partial 'commented.yaml'
}

@test "R2: PASSES the attribution against the workflow that does read it (#927)" {
  local _adr
  _adr="$(_write_adr payload_ok.md \
    '## Context' \
    '' \
    '- `.github/workflows/release-worker.yaml` (`on: workflow_call`)' \
    '  assembles the payload declared in' \
    '  `script/ci/release/archive.manifest` through' \
    '  `script/ci/release-archive.sh`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R2: a separate bullet is a separate claim (#927)" {
  # The block walk is what makes the fix expressible: one bullet per path,
  # each true of the workflow it names. Joined into one paragraph the same
  # two sentences are one claim about both workflows, and fail.
  local _adr
  _adr="$(_write_adr bullets.md \
    '## Context' \
    '' \
    '- A base tag runs the `release` job in' \
    '  `.github/workflows/self-test.yaml`, which assembles its archive' \
    '  itself.' \
    '- `.github/workflows/release-worker.yaml` is `on: workflow_call` only;' \
    '  it assembles the payload declared in' \
    '  `script/ci/release/archive.manifest`.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

# ════════════════════════════════════════════════════════════════════
# R3 -- quotation
# ════════════════════════════════════════════════════════════════════

@test "R3: FAILS a verbatim claim about a file outside this repo (#927)" {
  # The shipped defect: "reads, verbatim:" over a four-row table quoted
  # with three rows, from a harness-side skill no in-repo gate can open.
  local _adr
  _adr="$(_write_adr quote.md \
    '## Context' \
    '' \
    '`semver-bump`'"'"'s bump-classification table reads, verbatim:' \
    '' \
    '| Tag shape | Bump |' \
    '|---|---|' \
    '| `vX.Y.Z` | Z |')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_failure
  assert_output --partial 'verbatim'
}

@test "R3: PASSES a verbatim claim about a file this repo carries (#927)" {
  local _adr
  _adr="$(_write_adr quote_ok.md \
    '## Context' \
    '' \
    '`script/ci/release/archive.manifest` reads, verbatim:' \
    '' \
    '```text' \
    'Dockerfile' \
    '```')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}

@test "R3: IGNORES verbatim used about behaviour rather than a quotation (#927)" {
  # ADR-00000005 says `just` forwards its arguments verbatim; nothing is
  # being quoted, and the block does not introduce a quotation.
  local _adr
  _adr="$(_write_adr behaviour.md \
    '## Context' \
    '' \
    'It forwards `just run -t headless --gpus all` verbatim -- no' \
    'rewriting, no re-quoting.')"
  run _adr_claims "${_adr}" "${REPO}"
  assert_success
}
