#!/usr/bin/env bats
#
# Unit tests for script/release/release_notes.sh -- the assembler that turns
# a tag into the body of its GitHub release page.
#
# What it replaces, and why the replacement has to REFUSE. The release job
# in .github/workflows/self-test.yaml used to inline an awk one-liner that
# printed everything between `## [<tag>]` and the next `## [`, redirected
# into /tmp/release-notes.md, with nothing looking at the result. An awk
# that matches nothing exits 0 and writes an empty file, and
# softprops/action-gh-release accepts an empty body_path without complaint,
# so a doc-only edit that renamed or reformatted one heading would ship a
# release whose entire body was GitHub's autogenerated PR-title list --
# green CI, no warning, and the curated notes silently absent. Every case
# below that ends in a non-zero status exists because of that: the
# assembler's job is not only to find the section, it is to fail loudly
# when what it found is not release notes.
#
# The second thing it fixes is the promoted final release. This project cuts
# RCs and then promotes one unchanged, and the convention was to leave the
# entries under the RC headings that introduced them and give the final
# section a paragraph pointing at them. A reader of `v0.42.0` has no
# interest in which RC introduced what -- and measured on the real v0.42.0
# release page, the curated half of a 26,690-character body was five lines
# of pointer prose. So a final release's notes are the UNION of its RCs,
# merged category by category, which is also what makes the locked category
# roster pay for itself: merging is a few lines only because the headings
# are drawn from a known set.
#
# Fixtures are written into a scratch changelog directory so the spec is
# independent of the live tree; the last case drives the real one.

bats_require_minimum_version 1.5.0

setup() {
  export LOG_FORMAT=text
  load "${BATS_TEST_DIRNAME}/test_helper"

  NOTES=/source/script/release/release_notes.sh
  assert_spec_subject "${NOTES}" \
      "the release-notes assembler this spec pins"

  SCRATCH="$(mktemp -d)"
  CL="${SCRATCH}/changelog"
  mkdir -p "${CL}"
}

teardown() {
  [[ -n "${SCRATCH:-}" ]] && rm -rf "${SCRATCH}"
}

# _series <name> <line>... -- write one series file into the scratch
# changelog directory.
_series() {
  local _name="${1}"
  shift
  printf '%s\n' "$@" > "${CL}/${_name}.md"
}

@test "release_notes.sh: an RC tag's notes are that RC's own entries" {
  _series v0.9 \
    '# v0.9' \
    '' \
    '## [v0.9.0-rc2] - 2026-04-02' \
    '' \
    '### Fixed' \
    '- the second candidate fix (#2, PR #3)' \
    '' \
    '## [v0.9.0-rc1] - 2026-04-01' \
    '' \
    '### Added' \
    '- the first candidate feature (#1, PR #2)'

  run "${NOTES}" v0.9.0-rc2 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the second candidate fix (#2, PR #3)'
  refute_output --partial 'the first candidate feature'
  # The heading itself is not part of the body: the release page already
  # carries the tag as its title.
  refute_output --partial '## [v0.9.0-rc2]'
}

@test "release_notes.sh: a tag with no section DIES rather than emitting an empty body" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- something (#1, PR #2)'

  run "${NOTES}" v0.9.1 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.9.1'
}

@test "release_notes.sh: a section whose body carries no entry DIES" {
  # The measured v0.42.0 shape: a promoted final whose whole section is a
  # paragraph pointing at the RCs -- and, with no RC sections to union in,
  # nothing that reads as release notes.
  _series v0.42 \
    '## [v0.42.0] - 2026-08-25' \
    '' \
    '`v0.42.0-rc4` promoted unchanged -- the entries stay under the RC' \
    'headings that introduced them rather than being duplicated here.'

  run "${NOTES}" v0.42.0 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.42.0'
}

@test "release_notes.sh: a promoted final release's notes are the union of its RCs" {
  _series v0.42 \
    '## [v0.42.0] - 2026-08-25' \
    '' \
    '`v0.42.0-rc2` promoted unchanged -- the entries stay under the RC' \
    'headings that introduced them.' \
    '' \
    '## [v0.42.0-rc2] - 2026-08-20' \
    '' \
    '### Fixed' \
    '- the late fix (#20, PR #21)' \
    '' \
    '## [v0.42.0-rc1] - 2026-08-10' \
    '' \
    '### Added' \
    '- the early feature (#10, PR #11)' \
    '' \
    '### Fixed' \
    '- the early fix (#12, PR #13)'

  run "${NOTES}" v0.42.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the early feature (#10, PR #11)'
  assert_output --partial '- the early fix (#12, PR #13)'
  assert_output --partial '- the late fix (#20, PR #21)'
  # One heading per category across the whole union, not one per RC.
  [ "$(grep -c '^### Fixed$' <<< "${output}")" -eq 1 ]
  # The pointer paragraph is superseded by the entries it pointed at.
  refute_output --partial 'promoted unchanged'
}

@test "release_notes.sh: categories are emitted in the locked roster order" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Security' \
    '- s (#5, PR #6)' \
    '' \
    '### Fixed' \
    '- f (#4, PR #5)' \
    '' \
    '### Added' \
    '- a (#2, PR #3)' \
    '' \
    '### BREAKING' \
    '- b (#1, PR #2)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  [ "$(grep -n '^### ' <<< "${output}" | cut -d: -f2 | paste -sd,)" \
    = '### BREAKING,### Added,### Fixed,### Security' ]
}

@test "release_notes.sh: a final release with its own entries keeps its lead paragraph" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    'This release closes the 0.9 line.' \
    '' \
    '### Added' \
    '- the final-only entry (#30, PR #31)' \
    '' \
    '## [v0.9.0-rc1] - 2026-04-01' \
    '' \
    '### Added' \
    '- the candidate entry (#10, PR #11)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial 'This release closes the 0.9 line.'
  assert_output --partial '- the final-only entry (#30, PR #31)'
  assert_output --partial '- the candidate entry (#10, PR #11)'
}

@test "release_notes.sh: a '## [' inside a fenced block does not end the section" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- an entry that shows the file format (#1, PR #2)' \
    '' \
    '  ```markdown' \
    '  ## [v0.0.0] - 1970-01-01' \
    '  ```' \
    '' \
    '- the entry after the fence (#3, PR #4)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the entry after the fence (#3, PR #4)'
}

@test "release_notes.sh: the compare-link block is not part of the notes" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- an entry (#1, PR #2)' \
    '' \
    '[v0.9.0]: https://example.invalid/compare/v0.8.0...v0.9.0'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  refute_output --partial 'example.invalid'
}

@test "release_notes.sh: a tag present in two series files is refused" {
  # The split's own failure mode: a section copied rather than moved leaves
  # two answers to "what shipped in this tag", and picking either silently
  # is how the wrong one reaches a release page.
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- the entry in its own series file (#1, PR #2)'
  _series v0.8 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- the copy left behind (#1, PR #2)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.9.0'
}

@test "release_notes.sh: the live changelog tree answers for the current release" {
  # Non-vacuity against the real tree: whatever `.version` names must be
  # assemblable, so a heading reformatted by a doc-only change fails here
  # rather than on the release page.
  local _version
  _version="$(< /source/.version)"
  run "${NOTES}" "${_version}"
  [ "${status}" -eq 0 ]
  [ -n "${output}" ]
  assert_output --partial '- '
}
