#!/usr/bin/env bats
#
# Unit tests for script/release/release_notes.sh -- the assembler that turns
# a tag into the body of its GitHub release page.
#
# What it replaces, and why the replacement has to REFUSE. The release job
# in .github/workflows/self-test.yaml used to inline an awk one-liner that
# printed everything between `## [<tag>]` and the next `## [`, redirected
# into /tmp/release-notes.md, with nothing looking at the result. An awk
# that matches nothing exits 0 and writes an empty file, and
# softprops/action-gh-release accepts an empty body_path without complaint,
# so a doc-only edit that renamed or reformatted one heading would ship a
# release whose entire body was GitHub's autogenerated PR-title list --
# green CI, no warning, and the curated notes silently absent. Every case
# below that ends in a non-zero status exists because of that: the
# assembler's job is not only to find the section, it is to fail loudly
# when what it found is not release notes.
#
# The second thing it fixes is the promoted final release. This project cuts
# RCs and then promotes one unchanged, and the convention was to leave the
# entries under the RC headings that introduced them and give the final
# section a paragraph pointing at them. A reader of `v0.42.0` has no
# interest in which RC introduced what -- and measured on the real v0.42.0
# release page, the curated half of a 26,690-character body was five lines
# of pointer prose. So a final release's notes are the UNION of its RCs,
# merged category by category, which is also what makes the locked category
# roster pay for itself: merging is a few lines only because the headings
# are drawn from a known set.
#
# Fixtures are written into a scratch changelog directory so the spec is
# independent of the live tree; the last case drives the real one.

bats_require_minimum_version 1.5.0

setup() {
  export LOG_FORMAT=text
  load "${BATS_TEST_DIRNAME}/test_helper"

  NOTES=/source/script/release/release_notes.sh
  assert_spec_subject "${NOTES}" \
      "the release-notes assembler this spec pins"

  SCRATCH="$(mktemp -d)"
  CL="${SCRATCH}/changelog"
  mkdir -p "${CL}"
}

teardown() {
  [[ -n "${SCRATCH:-}" ]] && rm -rf "${SCRATCH}"
}

# _series <name> <line>... -- write one series file into the scratch
# changelog directory.
_series() {
  local _name="${1}"
  shift
  printf '%s\n' "$@" > "${CL}/${_name}.md"
}

# why: The base case the twelve below deviate from, and the one that pins that
# the `## [tag]` heading itself is NOT part of the body: the release page
# already prints the tag as its title, so emitting it again is a
# duplicated heading on every page.
@test "release_notes.sh: an RC tag's notes are that RC's own entries" {
  _series v0.9 \
    '# v0.9' \
    '' \
    '## [v0.9.0-rc2] - 2026-04-02' \
    '' \
    '### Fixed' \
    '- the second candidate fix (#2, PR #3)' \
    '' \
    '## [v0.9.0-rc1] - 2026-04-01' \
    '' \
    '### Added' \
    '- the first candidate feature (#1, PR #2)'

  run "${NOTES}" v0.9.0-rc2 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the second candidate fix (#2, PR #3)'
  refute_output --partial 'the first candidate feature'
  # The heading itself is not part of the body: the release page already
  # carries the tag as its title.
  refute_output --partial '## [v0.9.0-rc2]'
}

# why: The regression the whole script exists for. The awk it replaces exited 0
# on no match and wrote an empty file, which action-gh-release publishes
# without complaint, so a renamed heading shipped a release whose whole
# body was GitHub's PR-title list. Only a refusal makes that visible at
# tag push.
@test "release_notes.sh: a tag with no section DIES rather than emitting an empty body" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- something (#1, PR #2)'

  run "${NOTES}" v0.9.1 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.9.1'
}

# why: Finding the section is not the same question as finding release notes.
# The measured v0.42.0 shape is a promoted final whose entire section is a
# paragraph pointing at its RCs, so a check that only asks whether the tag
# was found passes on a body worth nothing to a reader.
@test "release_notes.sh: a section whose body carries no entry DIES" {
  # The measured v0.42.0 shape: a promoted final whose whole section is a
  # paragraph pointing at the RCs -- and, with no RC sections to union in,
  # nothing that reads as release notes.
  _series v0.42 \
    '## [v0.42.0] - 2026-08-25' \
    '' \
    '`v0.42.0-rc4` promoted unchanged -- the entries stay under the RC' \
    'headings that introduced them rather than being duplicated here.'

  run "${NOTES}" v0.42.0 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.42.0'
}

# why: This project cuts RCs and promotes one unchanged, so a final tag's own
# section is a pointer and the entries sit under headings a reader of
# vX.Y.0 has no interest in. One heading per category across the whole
# union is what makes the page complete without republishing RC structure
# as if it were history.
@test "release_notes.sh: a promoted final release's notes are the union of its RCs" {
  _series v0.42 \
    '## [v0.42.0] - 2026-08-25' \
    '' \
    '`v0.42.0-rc2` promoted unchanged -- the entries stay under the RC' \
    'headings that introduced them.' \
    '' \
    '## [v0.42.0-rc2] - 2026-08-20' \
    '' \
    '### Fixed' \
    '- the late fix (#20, PR #21)' \
    '' \
    '## [v0.42.0-rc1] - 2026-08-10' \
    '' \
    '### Added' \
    '- the early feature (#10, PR #11)' \
    '' \
    '### Fixed' \
    '- the early fix (#12, PR #13)'

  run "${NOTES}" v0.42.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the early feature (#10, PR #11)'
  assert_output --partial '- the early fix (#12, PR #13)'
  assert_output --partial '- the late fix (#20, PR #21)'
  # One heading per category across the whole union, not one per RC.
  [ "$(grep -c '^### Fixed$' <<< "${output}")" -eq 1 ]
  # The pointer paragraph is superseded by the entries it pointed at.
  refute_output --partial 'promoted unchanged'
}

# why: The union merges by category, which is a few lines only because the
# headings come from a known set. This is where the locked roster pays for
# itself: the page opens with BREAKING rather than in whatever order the
# RCs happened to land in.
@test "release_notes.sh: categories are emitted in the locked roster order" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Security' \
    '- s (#5, PR #6)' \
    '' \
    '### Fixed' \
    '- f (#4, PR #5)' \
    '' \
    '### Added' \
    '- a (#2, PR #3)' \
    '' \
    '### BREAKING' \
    '- b (#1, PR #2)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  [ "$(grep -n '^### ' <<< "${output}" | cut -d: -f2 | paste -sd,)" \
    = '### BREAKING,### Added,### Fixed,### Security' ]
}

# why: The union must add, not replace. A final release that says something of
# its own is the one part written for the release page itself, and losing
# it to the merge would silently delete the only prose a human aimed at
# that page.
@test "release_notes.sh: a final release with its own entries keeps its lead paragraph" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    'This release closes the 0.9 line.' \
    '' \
    '### Added' \
    '- the final-only entry (#30, PR #31)' \
    '' \
    '## [v0.9.0-rc1] - 2026-04-01' \
    '' \
    '### Added' \
    '- the candidate entry (#10, PR #11)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial 'This release closes the 0.9 line.'
  assert_output --partial '- the final-only entry (#30, PR #31)'
  assert_output --partial '- the candidate entry (#10, PR #11)'
}

# why: The guard tests the lead ARRAY's length, and a `## [tag]` heading is
# always followed by a blank line, so the array is never empty -- only
# ever blank. Every assembled body therefore opened with a stray blank
# line, on every release page, and nothing but an assertion on the first
# line can see it.
@test "release_notes.sh: a section with no lead paragraph does not open with a blank line" {
  # A `## [tag]` heading is always followed by a blank line, so the lead the
  # assembler collects is never an EMPTY array -- only ever an array of
  # blanks. A guard on its length therefore passes for a section that wrote
  # no lead at all, and the blank line is emitted ahead of the first
  # `### `: every assembled body opens with one, on every release page.
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- an entry (#1, PR #2)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  [ "${lines[0]}" = '### Added' ]
}

# why: The entry most likely to quote a section heading is the entry about the
# changelog's own format. A scan with no fence state truncates there and
# drops every entry after it, so the release documenting the split is the
# release the split silently shortens.
@test "release_notes.sh: a '## [' inside a fenced block does not end the section" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- an entry that shows the file format (#1, PR #2)' \
    '' \
    '  ```markdown' \
    '  ## [v0.0.0] - 1970-01-01' \
    '  ```' \
    '' \
    '- the entry after the fence (#3, PR #4)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  assert_output --partial '- the entry after the fence (#3, PR #4)'
}

# why: In a series file the link definitions follow the section directly, so a
# section that ends only at the next `## [` publishes reference data as
# page content. The split is what moved those definitions inside the span
# the assembler reads.
@test "release_notes.sh: the compare-link block is not part of the notes" {
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- an entry (#1, PR #2)' \
    '' \
    '[v0.9.0]: https://example.invalid/compare/v0.8.0...v0.9.0'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -eq 0 ]
  refute_output --partial 'example.invalid'
}

# why: The split's own failure mode: a section copied rather than moved leaves
# two answers to what shipped in this tag. Picking either silently puts
# one of them on a page nobody can correct afterwards, so the ambiguity is
# refused instead of ordered away.
@test "release_notes.sh: a tag present in two series files is refused" {
  # The split's own failure mode: a section copied rather than moved leaves
  # two answers to "what shipped in this tag", and picking either silently
  # is how the wrong one reaches a release page.
  _series v0.9 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- the entry in its own series file (#1, PR #2)'
  _series v0.8 \
    '## [v0.9.0] - 2026-04-03' \
    '' \
    '### Added' \
    '- the copy left behind (#1, PR #2)'

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial 'v0.9.0'
}

# why: Measured on the real tree: v0.42's RC union is 326,638 characters
# against GitHub's 125,000 cap, so the API answers the tag push with a 422
# after every gate has gone green. Refusing here fails the release with
# our message and both numbers, and refuses rather than truncates because
# a page silently missing entries is the failure this script exists to
# stop.
@test "release_notes.sh: a body over GitHub's release-body limit is refused, naming both numbers" {
  # Found by running the assembler over the real v0.42.0: the union of
  # rc1..rc4 is 326,638 characters, and GitHub caps a release body at
  # 125,000. Handing that to action-gh-release is a 422 at tag push, after
  # every gate has passed, with the API's message and not ours. Refusing
  # here says which release, how big, and against what limit -- and it is a
  # refusal rather than a silent truncation because a release page missing
  # the entries nobody was told were dropped is the failure this whole
  # script exists to stop.
  #
  # It is not retroactive and cannot be: the 700-character entry cap only
  # governs [Unreleased], so the sections that blow the limit are released
  # text nobody may rewrite. What the cap buys is that a release written
  # under it does not reach the limit -- 76 capped entries is about 38,000.
  local _pad
  _pad="$(printf 'x%.0s' $(seq 1 700))"
  {
    printf '## [v0.9.0] - 2026-04-03\n\n'
    printf '### Added\n'
    local _i
    for _i in $(seq 1 200); do
      printf -- '- **entry %s** (#%s, PR #%s) -- %s\n' "${_i}" "${_i}" "${_i}" "${_pad}"
    done
  } > "${CL}/v0.9.md"

  run "${NOTES}" v0.9.0 "${CL}"
  [ "${status}" -ne 0 ]
  assert_output --partial '125000'
  assert_output --partial 'v0.9.0'
}

# why: The regression stated as a property of the REAL tree rather than of a
# fixture, so it still holds for a version whose notes are too large to
# assemble. This is the assertion that would have caught a doc-only
# heading rename before the release job ran on it.
@test "release_notes.sh: the version being released has exactly one section in the live tree" {
  # The regression this whole file exists for, asserted against the real
  # tree: a doc-only change that renames or reformats a `## [vX.Y.Z]`
  # heading used to ship a release page carrying only autogenerated PR
  # titles. Asserted as a property of the TREE rather than by assembling,
  # so it holds for a version whose notes are too large to publish as they
  # stand (see the case below).
  local _version _hits
  _version="$(< /source/.version)"
  _hits="$(grep -rlF "## [${_version}]" /source/doc/changelog/ | wc -l)"
  [ "${_hits}" -eq 1 ] \
    || fail "'## [${_version}]' appears in ${_hits} files under doc/changelog/, expected exactly 1"
}

# why: Every other case drives a scratch fixture, so without this the spec
# could pass in full against a changelog shaped nothing like the one that
# ships. v0.41.0 rather than `.version`, because v0.42's released text
# predates the entry cap and is refused for size -- a fact about history,
# not about this script.
@test "release_notes.sh: a real released tag assembles from the live tree" {
  # v0.41.0 rather than .version: v0.42's sections predate the 700-character
  # entry cap, and its RC union measures 326,638 characters against
  # GitHub's 125,000 limit, so it is refused by the case above -- a fact
  # about released text nobody may rewrite, not about this script. v0.41.0
  # is a real single-version tag in the real tree and exercises the same
  # path end to end.
  run "${NOTES}" v0.41.0
  [ "${status}" -eq 0 ]
  assert_output --partial '- '
  assert_output --partial '### '
  # And it opens with content, not with the blank line that sits between a
  # `## [tag]` heading and its first category in every series file.
  [ -n "${lines[0]}" ]
}
